// types/index.ts

// This will be based on the types generated by 'npx supabase gen types'
// For now, we'll define the ones we need manually.
export interface Project {
  id: string;
  created_at: string;
  name: string;
  project_number: string;
  location: string;
  organization_id: string;
}